export const DEFAULT_PFP =
  "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAAA1UlEQVR4AcXBMUoFMRCA4f8NU+QkOYr9dNruIUS2N4jgFdJa5i6WU3uILQLPdtgisDxkvu/29ft8Z8FcecSokxUhmZBMSKacmCsro05WzJXIXIlGnURCMiGZkEzNlSvMlUeYK5GQTEgmJFNOvj9eiUpvPOLYdqKXt08iIZmQTEh2e3/6uROU3vhPx7YTCcmEZEIyLb1xxbHtrJTeWCm9EQnJhGRCMuXEXIlGnUSlN64wV6JRJ5GQTEgmJFNzJRp1Epkr0aiTFXMlGnUSmSuRkExIJiT7A+3GMx5oCAQQAAAAAElFTkSuQmCC";
export enum ChatType {
  ALL = "all",
  REQUESTS = "requests",
  PINNED = "pinned",
  ARCHIVED = "archived",
}
